treewide: Add void argument to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing arguments are
triggering the Wstrict-prototype warns. Explicitly add the
`void` argument to satisfy the compiler.

This fixes the following warnings:

../drivers/input/touchscreen/st/fts_lib/ftsIO.c:85:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void

../drivers/input/touchscreen/st/fts_lib/ftsIO.c:93:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct i2c_client *getClient()
                            ^
                             void

../drivers/input/touchscreen/st/fts_lib/ftsTime.c:95:16: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
char *timestamp()
               ^
                void

../drivers/video/fbdev/msm/mdss_mdp.c:4871:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct irq_info *mdss_intr_line()
                               ^
                                void

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1288:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:88:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void

../drivers/video/fbdev/msm/mdss_util.c:226:42: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct mdss_util_intf *mdss_get_util_intf()
                                         ^
                                          void

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/scan/dispatcher/src/wlan_extscan_api.c:103:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
wlan_extscan_global_deinit()
                          ^
                           void

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>

ok